config/routes.rb
Rails.application.routes.draw do

  resources :books
  devise_for :users

  devise_scope :user do
  authenticated :user do
    root 'books#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, :author_name, :year_published, :publisher, presence: true
  validates :name, :author_name, :publisher, length: { minimum: 2, maximum: 35 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

def index
  @books = Book.paginate(page: params[:page], per_page: 8).order('name ASC')
end


def show
  @book = Book.find_by(id:params[:id])
end

def new
  @book = Book.new
end

def create
  @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render 'new'
    end
end

def edit
  @book = Book.find_by(id:params[:id])
end

def update
  @book = Book.find_by(id:params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render 'edit'
    end
end

def destroy
  @book = Book.find_by(id:params[:id])
    if @book.destroy
      redirect_to books_path
    end
end

private
def book_params
  params.require(:book).permit(:name, :author_name, :year_published, :publisher)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def date_formatter(date)
    date.try(:strftime,  "%Y")
  end
end

app/helpers/format_helper.rb
module FormatHelper

end

app/views/books/_form.html.erb
<div class="form-group1">
	
	<%= form_for @book do |book| %>
		
		<%= book.label :name, class: "control-label" %>
		<%= book.text_field :name, class: "form-control",placeholder: "Name of book" %>


		<%= book.label :author_name, class: "control-label" %>
		<%= book.text_field :author_name, class: "form-control", placeholder: "Author name" %>



		<%= book.label :year_published, class: "control-label"%>
		<%= book.date_field :year_published, class: "form-control", id: "date_field" %>


		<%= book.label :publisher, class: "control-label" %>
		<%= book.text_field :publisher, class: "form-control", placeholder: "Publisher" %><br><br>

		<%= book.submit :submit, class: "btn btn-success btn-block" %>

	<% end %><br>
	<%= link_to 'Back', books_path %>

</div>

app/views/books/edit.html.erb
<% provide(:title, "Edit") %>

<div class="container-update">
	<div class="row">
		<div class="col-md-3"></div>

		<div class="col-md-6">
			<h3>Update Record:</h3>
			<%= render 'form' %>
		</div>
		
		<div class="col-md-3"></div>
	</div>	
</div>

app/views/books/index.html.erb
<% provide(:title, "Home") %>

<div class="container-index">

		<% if notice %><p class="notice"><%= notice %></p><% end %>
	  <% if alert %><p class="alert"><%= alert %></p><% end %>

	<div style="float:right;">
		<% if user_signed_in? %>
	  	<p>Welcome, <%= current_user.email %></p>
	  	<%= link_to 'Profile',edit_user_registration_path %> |
	  	<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
		<% else %>
	  	<p>You are not signed in.</p>
	  	<%= link_to 'Login', new_user_session_path %>
		<% end %>

	</div>

	<h3>Book Records:</h3>

	<%= link_to 'Create new record', new_book_path %>

	<table class="table table-bordered table-hover">
		<thead>
			<th>Name of Book</th>
			<th>Author Name</th>
			<th>Year Published</th>
			<th>Publisher</th>
			<th>Actions</th>
		</thead>

	<% @books.each do |book| %>
		<tbody>
			<td><%= (book.name).titleize %></td>
			<td><%= (book.author_name).titleize %></td>
			<td><%= date_formatter(book.year_published) %></td>
			<td><%= (book.publisher).titleize %></td>
			<td>
					<%= link_to 'Show',book_path(book) %>
					<% if user_signed_in? %> |
					<%= link_to 'Edit',edit_book_path(book) %> |
					<%= link_to 'Delete',book,method: :delete, data: {confirm: "Are you sure you want to delete this record?"} %>
					<% end %>
			</td>
		</tbody>
	<% end %>
	</table>

	<%= will_paginate @books %>

</div>

app/views/books/new.html.erb
<% provide(:title, "New") %>

<div class="container-update">
	<div class="row">
		<div class="col-md-3"></div>

		<div class="col-md-6">
			<h3>Create New Record:</h3>
			<%= render 'form' %>
		</div>
		
		<div class="col-md-3"></div>
	</div>	
</div>

app/views/books/show.html.erb
<% provide(:title, "Show") %>

<div class="container-index">

	<h3>Book</h3>

	<table class="table table-bordered">
		
		<thead>
			<tr>
				<th>Name of Book</th>
				<th>Author Name</th>
				<th>Year Published</th>
				<th>Publisher</th>
			</tr>
		</thead>

		<tbody>
			<tr>
				<td><%= @book.name %></td>
				<td><%= @book.author_name %></td>
				<td><%= date_formatter(@book.year_published) %></td>
				<td><%= @book.publisher %></td>
			</tr>
		</tbody>

	</table>

	<%= link_to 'Back',books_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Book Records</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>